// Takes geojson output from http://overpass-turbo.eu/
// Query

/*
This has been generated by the overpass-turbo wizard.
“crop=coffee”

[out:json][timeout:25];
(
  node["crop"="coffee"]({{bbox}});
  way["crop"="coffee"]({{bbox}});
  relation["crop"="coffee"]({{bbox}});
);
out body;
>;
out skel qt;
*/

var turf 	= require('turf')
var fs		= require('fs')

var fname		= process.argv[2]
var outname		= process.argv[3]

console.log("infile", fname)
console.log("outfile", outname)

if (!fs.existsSync(fname) ) {
	console.log("Invalid input file")
	process.exit(-1)
}
	
var collection	=  JSON.parse(fs.readFileSync(fname, 'utf8'));
var features = []

for( var f in collection.features ) {
	var feature = collection.features[f]
	var type = feature.geometry.type
	if( type=='Polygon') {
		var centroid = turf.centroid(feature)
		feature.geometry = centroid.geometry
	}
	
	features.push(feature)
}
collection.features = features	
console.log("writing features:", features.length)
fs.writeFileSync(outname, JSON.stringify(collection,null,'\t'), 'utf8')
console.log("Done")
