#
# ojo-bot production stack for Heroku
#
# Pat Cappelaere Vightel
# pat@cappelaere.com
#
# This used to buld a heroku slug using herok docker:release and building: web form docker-compose

FROM cappelaere/ojo_publisher_base_stack:v1

MAINTAINER Pat Cappelaere <pat@cappelaere.com>

#
# Data directory is mapped to /app/tmp in docker-compose
#

COPY app 			/app/user/app
COPY config			/app/user/config
COPY lib			/app/user/lib
COPY locale			/app/user/locale
COPY models			/app/user/models
COPY public			/app/user/public
COPY python			/app/user/python

COPY server.js		/app/user/server.js
COPY qserver.js		/app/user/qserver.js
COPY settings.js	/app/user/settings.js
COPY package.json	/app/user/package.json
COPY README.md		/app/user/README.md
#COPY Procfile		/app/user

COPY envs.docker.sh /app/user/envs.docker.sh
# Add to .basrc to have envs available when you run the shell
RUN echo 'source /app/user/envs.docker.sh' >> ~/.bashrc
COPY envs.docker.sh /etc/profile.d

WORKDIR /app/user
RUN npm install

